### PR TITLE
Added validations for destFolder

### PR DESCRIPTION
**Pull request by RemyJeancolas**
To be considered valid, `destFolder`:
* Must be a directory
* Must be writable

The unit tests have been updated accordingly.

### CODE REVIEW

**Comment by RemyJeancolas** [comment]
Hey @hgouveia, it looks like my PR is failing the tests because of a known limitation of Node.js about **chmod** on Windows (according to the first lines of the CI log, it looks like Appveyor is running a Windows version of Node).

This limitation is part of the [**official fs documentation**](https://nodejs.org/api/fs.html#fs_fs_mkdir_path_options_callback) (there is a comment for the `mode` parameter on mkdir, which also applies on the `chmod` function)

Although I think that checking if the directory is writable makes totally sense, I don't want to mock the fs module in the tests just to make it pass.
What would recommend in this very particular case ?

Thanks in advance for your answer.

**Comment by hgouveia** [comment]
> Hey @hgouveia, it looks like my PR is failing the tests because of a known limitation of Node.js about **chmod** on Windows (according to the first lines of the CI log, it looks like Appveyor is running a Windows version of Node).
> 
> This limitation is part of the [**official fs documentation**](https://nodejs.org/api/fs.html#fs_fs_mkdir_path_options_callback) (there is a comment for the `mode` parameter on mkdir, which also applies on the `chmod` function)
> 
> Although I think that checking if the directory is writable makes totally sense, I don't want to mock the fs module in the tests just to make it pass.
> What would recommend in this very particular case ?
> 
> Thanks in advance for your answer.

Hello @RemyJeancolas , first at all thanks for the contributions loved the work you did, 

Yeap, I'm using appveyor  in order to test if it is also working properly on windows, since as you mentioned sometimes node behaves differently in each OS

I was thinking that a solution could be replacing accessSync with openSync
```
fs.open(path, 'r+', fs.constants.W_OK, (err) => {}); //or fs.openSync
```
this will give you a `err.code = 'EPERM'` if doesn't has to permissions, I've used this in the past but only with files, not sure it works too with folder, could you give it a try?

**Comment by RemyJeancolas** [comment]
Hi @hgouveia, unfortunately `fs.open` (or `openSync`) only works with files, not directories (I gave it a shot to verify but it simply doesn't work).
Regarding the current situation, I see 4 ways to fix this issue:

* Use `os.arch()` to detect the running OS and not run this test if on Windows (quick and dirty)
* Remove this unit test (because it's trivial, even though I don't really like the idea of removing meaningful tests)
* Remove this validation directly from the source code: no code = no test (even though this validation makes sense)
* Use a mocking library (like [**sinon**](https://sinonjs.org/) or [**jest**](https://jestjs.io/)) to properly mock the `fs` module during the tests 

I would personally go with the mocking library (even though it involves refactoring the unit tests), but ultimately the choice is yours.
I don't mind working on this refactor, let me know if you want to give it a shot.

**Comment by hgouveia** [comment]
> Hi @hgouveia, unfortunately `fs.open` (or `openSync`) only works with files, not directories (I gave it a shot to verify but it simply doesn't work).
> Regarding the current situation, I see 4 ways to fix this issue:
> 
> * Use `os.arch()` to detect the running OS and not run this test if on Windows (quick and dirty)
> * Remove this unit test (because it's trivial, despite the fact that I don't really like the idea of removing meaningful tests)
> * Remove this validation directly from the source code: no code = no test (even though this validation makes sense)
> * Use a mocking library (like [**sinon**](https://sinonjs.org/) or [**jest**](https://jestjs.io/)) to properly mock the `fs` module during the tests
> 
> I would personally go with the mocking library (even though it involves refactoring the unit tests), but ultimately the choice is yours.
> I don't mind working on this refactor, let me know if you want to give it a shot.

Hello @RemyJeancolas, yeap I prefer to cover this test, I also agree that makes sense to use a mockery library, I will go with Jest since I am more familiar, but avoid adding information into the package.json I think is cleaner to have a separate `jest.config.js`

**Comment by RemyJeancolas** [comment]
> Hello @RemyJeancolas, yeap I prefer to cover this test, I also agree that makes sense to use a mockery library, I will go with Jest since I am more familiar, but avoid adding information into the package.json I think is cleaner to have a separate `jest.config.js`

Hi @hgouveia, I think it's good to go, let me know in case you have questions.

**Comment by hgouveia** [comment]
> > Hello @RemyJeancolas, yeap I prefer to cover this test, I also agree that makes sense to use a mockery library, I will go with Jest since I am more familiar, but avoid adding information into the package.json I think is cleaner to have a separate `jest.config.js`
> 
> Hi @hgouveia, I think it's good to go, let me know in case you have questions.

Great work thanks for your contribution!

**Pull request merged**
