### PR TITLE
Enforcement Breakpoint Continuation Option

### PR DESCRIPTION
**Pull request by shenlanchenwei**
Add Enforcement Breakpoint Continuation Option

### CODE REVIEW

**Comment by hgouveia** [comment]
Hello @shenlanchenwei , thanks for you contribution

i've checked the changes, but for my point of view, this new option , wont work correctly, since if you force the lib to be resumable and the server where you want to download the file doesn't support it, you will endup with a corrupted file , because if the download is paused, and you resume it again, is very likely the data you will get from the server will start from the beginning and the library will append this data to the file  instead of append from the last byte it downloaded

**Comment by shenlanchenwei** [comment]
Hi,@hgouveia 
The situation I encountered was that the server supported the resume of the breakpoint, but did not return to support the resume of the breakpoint, so it can only be set manually. This is the case when I know the server supports it.

**Comment by hgouveia** [comment]
> Hi,@hgouveia
> The situation I encountered was that the server supported the resume of the breakpoint, but did not return to support the resume of the breakpoint, so it can only be set manually. This is the case when I know the server supports it.

Hello @shenlanchenwei !, do you own that server? this situation seems to be very specify and no applicable to another users, in this case i think is better to fix the Server side to add the necessary header on the server side

**Comment by shenlanchenwei** [comment]
Hello @hgouveia,
The link https://gz.bcebos.com/v1/hone-im/test1/2018-11-19/09-46-45-128/xmind-pro-8-windows-v3.7.7.0.exe
You Can Test this,This is a Chinese cdn service provider.

**Comment by hgouveia** [comment]
> Hello @hgouveia,
> The link https://gz.bcebos.com/v1/hone-im/test1/2018-11-19/09-46-45-128/xmind-pro-8-windows-v3.7.7.0.exe
> You Can Test this,This is a Chinese cdn service provider.

Hello @shenlanchenwei  !

I did a test with the url you provided me,  i confirmed that this server doest show the proper header but it does support resume, after some testing while pausing and resume , it worked fine 👍 

i compared the checksum of both file and was the same, so this confirm the file wasnt corrupted

Download from Firefox
```
bash -c "sha1sum ./example/xmind-pro-8-windows-v3.7.7.0_firefox.exe"
13d9f6cd60efce906e363e161807b24b6dc68be0  ./example/xmind-pro-8-windows-v3.7.7.0_firefox.exe
```

Downloaded with this lib, while pausing for 1min
```
bash -c "sha1sum ./example/xmind-pro-8-windows-v3.7.7.0_downloader.exe"
13d9f6cd60efce906e363e161807b24b6dc68be0  ./example/xmind-pro-8-windows-v3.7.7.0_downloader.exe
```

So your PR will be merge ! 😄  ,but before that, could you rename the option from `enforcementResumable` to  `forceResume` ? i think is more clear in this way , also could you update the `README.md` adding this option on the "Options" snippet with some comment what it does?

Thanks

**Pull request merged**
